### PR TITLE
Show version number in footer

### PR DESCRIPTION
**Pull request by Mr0grog**
Quickie implementation of @bensheldon’s suggestion in #78.

Here’s how it looks right now on large and small screens:

version_number_preview

Happy to modify if anybody has feedback.

### CODE REVIEW

**Comment by bensheldon** [comment]
That looks great! :+1:

...now we just have to remember to cut releases and keep it updated :-)

**Comment by bensheldon** [comment]
And probably have a Changelog too.

**Comment by Mr0grog** [comment]
Ah, good point. CHANGELOGGING.

**Comment by Mr0grog** [comment]
Added a changelog and tried to fill it in with retroactive info. I know some of the work since v1.0.2 has actually shipped (not much, though), but I guess we never tagged a version for that :\

**Comment by Mr0grog** [comment]
Ok, think I’m gonna merge this in at the end of the day today (Chicago time).

**Pull request merged**
